;; ~/.config/nyxt/config.lisp
;; BlueAK Nyxt configuration

;; Load the active theme (generated by set-nyxt-theme)
;; If no theme is set yet, Eldritch is the default
(load-file #P"~/.config/nyxt/theme.lisp")