#!/usr/bin/env python3
"""
generate-nyxt-theme.py
Reads the active Noctalia colorscheme, writes a fresh noctalia-theme.lisp,
then restarts Nyxt so the new theme takes effect.
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

SETTINGS_PATH = Path.home() / ".config/noctalia/settings.json"
SCHEMES_DIR   = Path.home() / ".config/noctalia/colorschemes"
COLORS_PATH   = Path.home() / ".config/noctalia/colors.json"
OUTPUT_PATH   = Path.home() / ".config/nyxt/noctalia-theme.lisp"

def get_active_scheme():
    with open(SETTINGS_PATH) as f:
        settings = json.load(f)
    color_schemes = settings.get("colorSchemes", {})
    is_dark = color_schemes.get("darkMode", True)
    scheme_name = (
        color_schemes.get("predefinedScheme")
        or color_schemes.get("customScheme")
        or "Purple Haze"
    )
    return scheme_name, is_dark

def extract_terminal_colors(mode):
    terminal = mode.get("terminal")
    if not terminal:
        return None
    normal = terminal["normal"]
    bright = terminal["bright"]
    return {
        "bg":              terminal["background"],
        "fg":              terminal["foreground"],
        "bg_alt":          bright["black"],
        "green":           normal["green"],
        "blue":            normal["blue"],
        "magenta":         normal["magenta"],
        "bright_blue":     bright["blue"],
        "bright_magenta":  bright["magenta"],
        "red":             normal["red"],
        "cyan":            normal["cyan"],
        "yellow":          normal["yellow"],
        "sel_bg":          terminal.get("selectionBg", "#4E2478"),
        "sel_fg":          terminal.get("selectionFg", "#F0ECFF"),
        "cursor":          terminal.get("cursor", "#A8E000"),
        "surface_variant": mode.get("mSurfaceVariant", "#241330"),
        "on_surface":      mode.get("mOnSurface", "#E0DCF0"),
    }

def get_colors(scheme_name, is_dark):
    scheme_path = SCHEMES_DIR / scheme_name / f"{scheme_name}.json"
    if not scheme_path.exists():
        candidates = list(SCHEMES_DIR.glob(f"**/{scheme_name}.json"))
        scheme_path = candidates[0] if candidates else None

    if scheme_path:
        with open(scheme_path) as f:
            data = json.load(f)
        mode_key = "dark" if is_dark else "light"
        mode = data.get(mode_key) or data.get("dark") or data.get("light")
        colors = extract_terminal_colors(mode)
        if colors:
            print(f"Loaded from scheme file: {scheme_path}")
            return colors

    print(f"Scheme file not found for '{scheme_name}', falling back to colors.json")
    if not COLORS_PATH.exists():
        print(f"ERROR: {COLORS_PATH} not found", file=sys.stderr)
        sys.exit(1)

    with open(COLORS_PATH) as f:
        data = json.load(f)

    return {
        "bg":              data.get("mSurface",           "#0c070d"),
        "fg":              data.get("mOnSurface",          "#e0dcf0"),
        "bg_alt":          data.get("mHover",              "#241330"),
        "green":           data.get("mPrimary",            "#a8e000"),
        "blue":            data.get("mSecondary",          "#8a4fb0"),
        "magenta":         data.get("mTertiary",           "#aa7ad0"),
        "bright_blue":     data.get("mOnSurfaceVariant",   "#9878c0"),
        "bright_magenta":  data.get("mTertiary",           "#aa7ad0"),
        "red":             data.get("mError",              "#ff3c4e"),
        "cyan":            data.get("mTertiary",           "#aa7ad0"),
        "yellow":          data.get("mPrimary",            "#a8e000"),
        "sel_bg":          data.get("mHover",              "#241330"),
        "sel_fg":          data.get("mOnSurface",          "#e0dcf0"),
        "cursor":          data.get("mPrimary",            "#a8e000"),
        "surface_variant": data.get("mSurfaceVariant",     "#241330"),
        "on_surface":      data.get("mOnSurface",          "#e0dcf0"),
    }

def build_lisp(c, scheme_name):
    bg              = c['bg']
    fg              = c['fg']
    bg_alt          = c['bg_alt']
    green           = c['green']
    blue            = c['blue']
    magenta         = c['magenta']
    bright_blue     = c['bright_blue']
    sel_bg          = c['sel_bg']
    sel_fg          = c['sel_fg']
    surface_variant = c['surface_variant']

    return f'''\
;;; noctalia-theme.lisp
;;; AUTO-GENERATED by generate-nyxt-theme.py — do not edit manually.
;;; Active scheme: {scheme_name}

(in-package :nyxt-user)

;;; ── Web page dark mode ───────────────────────────────────────────────────
(define-configuration web-buffer
  ((default-modes (pushnew 'nyxt/mode/style:dark-mode %slot-value%))))

(define-configuration nyxt/mode/style:dark-mode
  ((style
    (str:concat
     "html,body{{background-color:{bg} !important;color:{fg} !important}}"
     "pre,code,kbd{{background-color:{surface_variant} !important;color:{fg} !important;border-radius:3px;padding:2px 4px}}"
     "blockquote{{background-color:{surface_variant};border-left:3px solid {blue};padding:8px;margin:4px}}"
     "table{{background-color:{surface_variant} !important;color:{fg} !important}}"
     "th{{background-color:{surface_variant} !important;color:{green} !important}}"
     "td{{border-color:{surface_variant} !important}}"
     "hr{{border-color:{surface_variant}}}"
     "h1,h2,h3,h4,h5,h6{{color:{green} !important}}"
     "a:link{{color:{green} !important}}"
     "a:visited{{color:{magenta} !important}}"
     "a:hover{{color:{bright_blue} !important}}"
     "input,textarea,select{{background-color:{surface_variant} !important;color:{fg} !important;border:1px solid {blue} !important;border-radius:3px}}"
     "input:focus,textarea:focus{{border-color:{green} !important;outline:none}}"
     "button,input[type=submit],input[type=button]{{background-color:{surface_variant} !important;color:{fg} !important;border:1px solid {blue} !important;border-radius:3px}}"
     "button:hover,input[type=submit]:hover{{background-color:{bg_alt} !important;border-color:{green} !important}}"
     "::selection{{background-color:{sel_bg} !important;color:{sel_fg} !important}}"
     "::-webkit-scrollbar{{background-color:{bg};width:8px}}"
     "::-webkit-scrollbar-thumb{{background-color:{surface_variant};border-radius:4px}}"
     "::-webkit-scrollbar-thumb:hover{{background-color:{blue}}}"
     "img,video{{opacity:0.9 !important}}"))))

;;; ── Nyxt UI theme ────────────────────────────────────────────────────────
(define-configuration browser
  ((remote-execution-p t)
   (theme
    (make-instance 'theme:theme
      :dark-p           t
      :background-color "{bg}"
      :text-color       "{fg}"
      :primary-color    "{blue}"
      :secondary-color  "{surface_variant}"
      :tertiary-color   "{bg_alt}"
      :quaternary-color "{surface_variant}"
      :accent-color     "{green}"))))
'''

def restart_nyxt():
    env = os.environ.copy()
    env.setdefault("WAYLAND_DISPLAY", "wayland-1")
    env.setdefault("DBUS_SESSION_BUS_ADDRESS", f"unix:path=/run/user/{os.getuid()}/bus")
    env.setdefault("XDG_RUNTIME_DIR", f"/run/user/{os.getuid()}")

    print("Killing Nyxt...")
    subprocess.run(["flatpak", "kill", "engineer.atlas.Nyxt"], env=env)

    print("Waiting for Nyxt to exit...")
    time.sleep(2)

    print("Restarting Nyxt...")
    subprocess.Popen(
        ["flatpak", "run", "engineer.atlas.Nyxt"],
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True
    )

def main():
    if not SETTINGS_PATH.exists():
        print(f"ERROR: {SETTINGS_PATH} not found", file=sys.stderr)
        sys.exit(1)

    scheme_name, is_dark = get_active_scheme()
    print(f"Active scheme: {scheme_name} ({'dark' if is_dark else 'light'})")

    colors = get_colors(scheme_name, is_dark)
    lisp   = build_lisp(colors, scheme_name)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write(lisp)
    print(f"Wrote {OUTPUT_PATH}")

    time.sleep(1)
    restart_nyxt()
    print("Done.")

if __name__ == "__main__":
    main()